import { useTranslation } from "react-i18next";
import { useState } from "react";

import "../styles/PregnancyCalculator.css";

import CalculatorLayout from "../components/CalculatorLayout";

import {
  calculatePregnancy,
  isValidPregnancyDate,
} from "../utils/pregnancyCalculatorLogic";
import ResultAttribution from "../components/ResultAttribution";

import DateInput from "../components/DateInput";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

function PregnancyCalculator() {

  const { t } = useTranslation();

  const [lmpDate, setLmpDate] = useState("");
  const [calculationDate, setCalculationDate] = useState("");
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [actionMessage, setActionMessage] = useState("");

  const [lmpResetKey, setLmpResetKey] = useState(0);
  const [calculationResetKey, setCalculationResetKey] = useState(0);


  /* =========================================================
     CALCULATE
  ========================================================= */

  function handleCalculate(event) {

    event.preventDefault();

    setError("");
    setResult(null);
    setActionMessage("");

    if (!lmpDate) {
      setError(
        "Please enter the first day of your last menstrual period."
      );
      return;
    }

    if (!isValidPregnancyDate(lmpDate)) {
      setError("Please enter a valid LMP date.");
      return;
    }

    if (
      calculationDate &&
      !isValidPregnancyDate(calculationDate)
    ) {
      setError("Please enter a valid calculation date.");
      return;
    }

    const data = calculatePregnancy(
      lmpDate,
      calculationDate
    );

    if (!data) {
      setError(
        "Unable to calculate pregnancy details."
      );
      return;
    }

    setResult(data);
  }


  /* =========================================================
     RESET
  ========================================================= */

  function handleReset() {

    setLmpDate("");
    setCalculationDate("");

    setResult(null);
    setError("");
    setActionMessage("");

    setLmpResetKey((key) => key + 1);
    setCalculationResetKey((key) => key + 1);
  }


  /* =========================================================
     RESULT TEXT
  ========================================================= */

  function getResultText() {

    if (!result) {
      return "";
    }

    let text = "";

    text += "AGEVERSE — PREGNANCY CALCULATOR\n";
    text += "================================\n\n";

    text += `Last Menstrual Period: ${result.lmpDate}\n`;
    text += `Estimated Due Date: ${result.dueDate}\n`;
    text += `Due Date: ${result.dueDateWithDay}\n`;
    text += `Calculation Date: ${result.calculationDate}\n\n`;

    if (result.status === "not-started") {

      text += "Status: Pregnancy Not Started\n";
      text += `${result.message}\n`;
    }

    if (result.status !== "not-started") {

      text +=
        `Pregnancy Age: ${result.weeks} Weeks ${result.days} Days\n`;

      text +=
        `Total Pregnancy Days: ${result.pregnancyDays}\n`;

      text +=
        `Trimester: ${result.trimester.name}\n`;

      text +=
        `Pregnancy Progress: ${result.progressPercent}%\n`;

      if (result.status === "ongoing") {

        text +=
          `Estimated Time Remaining: ${result.remainingDays} Days\n`;
      }

      if (result.status === "due-or-past") {

        text +=
          "Status: Estimated Due Date Reached or Passed\n";
      }
    }

    text += "\n";

    text +=
      "Important: This calculator provides an estimated pregnancy timeline based on the date entered. It is intended for general informational purposes only and should not be used as a substitute for medical diagnosis, treatment, or advice from a qualified healthcare professional. Pregnancy dates can vary, and your healthcare provider should be consulted for accurate assessment and clinical decisions.\n\n";

    text += "Generated by AgeVerse.Global";

    return text;
  }


  /* =========================================================
     COPY
  ========================================================= */

  /*
 * =========================================================
 * COPY — RICH / FORMATTED RESULT
 * =========================================================
 */

async function handleCopy() {

  if (!result) {
    return;
  }

  const resultCard =
    document.querySelector(
      ".pregnancy-result-card"
    );

  if (!resultCard) {
    setActionMessage(
      "Unable to copy the result."
    );

    return;
  }

  try {

    /*
     * Clone the result card so the visible
     * calculator is not modified.
     */

    const clone =
      resultCard.cloneNode(true);

    /*
     * Remove action buttons and temporary
     * action message from copied content.
     */

    const actions =
      clone.querySelector(
        ".pregnancy-result-actions"
      );

    if (actions) {
      actions.remove();
    }

    const actionMessage =
      clone.querySelector(
        ".pregnancy-action-message"
      );

    if (actionMessage) {
      actionMessage.remove();
    }

    /*
     * Create a clean wrapper for
     * rich HTML clipboard content.
     */

    const wrapper =
      document.createElement("div");

    wrapper.style.fontFamily =
      "Arial, Helvetica, sans-serif";

    wrapper.style.maxWidth =
      "760px";

    wrapper.style.margin =
      "0 auto";

    wrapper.style.background =
      "#ffffff";

    wrapper.style.color =
      "#334155";

    wrapper.appendChild(
      clone
    );

    /*
     * Create both:
     *
     * 1. HTML version
     * 2. Plain-text fallback
     */

    const html =
      wrapper.innerHTML;

    const plainText =
      getResultText();

    /*
     * Modern Clipboard API
     * with HTML formatting.
     */

    if (
      navigator.clipboard &&
      window.ClipboardItem &&
      window.isSecureContext
    ) {

      const clipboardItem =
        new ClipboardItem({
          "text/html":
            new Blob(
              [html],
              {
                type:
                  "text/html",
              }
            ),

          "text/plain":
            new Blob(
              [plainText],
              {
                type:
                  "text/plain",
              }
            ),
        });

      await navigator.clipboard.write([
        clipboardItem,
      ]);

    } else {

      /*
       * Fallback for browsers where
       * ClipboardItem is unavailable.
       */

      const selection =
        window.getSelection();

      const range =
        document.createRange();

      const temporary =
        document.createElement("div");

      temporary.style.position =
        "fixed";

      temporary.style.left =
        "-10000px";

      temporary.style.top =
        "0";

      temporary.style.width =
        "760px";

      temporary.style.background =
        "#ffffff";

      temporary.innerHTML =
        html;

      document.body.appendChild(
        temporary
      );

      range.selectNodeContents(
        temporary
      );

      selection.removeAllRanges();

      selection.addRange(
        range
      );

      document.execCommand(
        "copy"
      );

      selection.removeAllRanges();

      document.body.removeChild(
        temporary
      );
    }

    setActionMessage(
      "✓ Formatted pregnancy result copied successfully."
    );

  } catch (error) {

    console.error(
      "Pregnancy Copy Error:",
      error
    );

    /*
     * Final fallback:
     * copy plain text if rich copy fails.
     */

    try {

      await navigator.clipboard.writeText(
        getResultText()
      );

      setActionMessage(
        "✓ Result copied successfully."
      );

    } catch (fallbackError) {

      setActionMessage(
        "Unable to copy the result."
      );
    }
  }
}


  /* =========================================================
     SHARE
  ========================================================= */

  async function handleShare() {

    if (!result) return;

    const text = getResultText();

    try {

      if (navigator.share) {

        await navigator.share({
          title:
            "AgeVerse Pregnancy Calculator",
          text,
        });

        setActionMessage(
          "✓ Pregnancy result shared successfully."
        );

      } else {

        await handleCopy();
      }

    } catch (error) {

      if (error?.name === "AbortError") {
        return;
      }

      setActionMessage(
        "Unable to share the pregnancy result."
      );
    }
  }


  /* =========================================================
     DOWNLOAD — PROFESSIONAL HTML RESULT
  ========================================================= */

  /*
 * =========================================================
 * DOWNLOAD — PDF
 * Downloads the Pregnancy Result Card as a styled PDF
 * =========================================================
 */

async function handleDownload() {

  if (!result) {
    return;
  }

  const resultCard =
    document.querySelector(
      ".pregnancy-result-card"
    );

  if (!resultCard) {
    setActionMessage(
      "Unable to generate PDF."
    );

    return;
  }

  setActionMessage(
    "Preparing PDF..."
  );

  try {

    /*
     * Clone result card so PDF generation
     * does not disturb the visible UI.
     */

    const clone =
      resultCard.cloneNode(true);

    /*
     * Remove action buttons and action message
     * from downloaded PDF.
     */

    const actions =
      clone.querySelector(
        ".pregnancy-result-actions"
      );

    if (actions) {
      actions.remove();
    }

    const actionMessage =
      clone.querySelector(
        ".pregnancy-action-message"
      );

    if (actionMessage) {
      actionMessage.remove();
    }

    /*
     * Create temporary rendering container.
     */

    const container =
      document.createElement("div");

    container.style.position =
      "fixed";

    container.style.left =
      "-10000px";

    container.style.top =
      "0";

    container.style.width =
      "760px";

    container.style.background =
      "#ffffff";

    container.style.padding =
      "20px";

    container.style.boxSizing =
      "border-box";

    container.style.zIndex =
      "-1";

    container.appendChild(clone);

    document.body.appendChild(
      container
    );

    /*
     * Convert styled HTML card to canvas.
     */

    const canvas =
      await html2canvas(
        clone,
        {
          scale: 2,
          useCORS: true,
          backgroundColor:
            "#ffffff",
        }
      );

    /*
     * Remove temporary container.
     */

    document.body.removeChild(
      container
    );

    /*
     * Create PDF.
     */

    const pdf =
      new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

    const pageWidth =
      pdf.internal.pageSize.getWidth();

    const pageHeight =
      pdf.internal.pageSize.getHeight();

    const margin = 10;

    const availableWidth =
      pageWidth -
      margin * 2;

    const imageWidth =
      canvas.width;

    const imageHeight =
      canvas.height;

    const imageRatio =
      imageHeight /
      imageWidth;

    const pdfImageHeight =
      availableWidth *
      imageRatio;

    /*
     * If the card fits on one A4 page,
     * keep it on one page.
     */

    if (
      pdfImageHeight <=
      pageHeight - margin * 2
    ) {

      pdf.addImage(
        canvas,
        "PNG",
        margin,
        margin,
        availableWidth,
        pdfImageHeight
      );

    } else {

      /*
       * Scale the complete result card
       * to fit on ONE A4 page.
       */

      const fittedHeight =
        pageHeight -
        margin * 2;

      const fittedWidth =
        fittedHeight /
        imageRatio;

      const x =
        (pageWidth -
          fittedWidth) / 2;

      pdf.addImage(
        canvas,
        "PNG",
        x,
        margin,
        fittedWidth,
        fittedHeight
      );
    }

    /*
     * Save PDF.
     */

    pdf.save(
      "AgeVerse-Pregnancy-Result.pdf"
    );

    setActionMessage(
      "✓ Pregnancy result PDF downloaded successfully."
    );

  } catch (error) {

    console.error(
      "Pregnancy PDF Error:",
      error
    );

    /*
     * Remove temporary container
     * if an error occurred.
     */

    const temporaryContainer =
      document.querySelector(
        'body > div[style*="-10000px"]'
      );

    if (
      temporaryContainer
    ) {
      temporaryContainer.remove();
    }

    setActionMessage(
      "Unable to generate PDF. Please try again."
    );
  }
}


  /* =========================================================
     DOWNLOAD HTML BUILDER
  ========================================================= */

  function buildDownloadHTML() {

    const ongoing =
      result.status !== "not-started";

    const remaining =
      result.status === "ongoing"
        ? `
          <div class="remaining box">
            <div class="label">⏳ Estimated Time Remaining</div>
            <div class="value">
              ${result.remainingDays} Days
            </div>
            <div class="sub">
              Until estimated due date
            </div>
          </div>
        `
        : "";

    const pregnancyDetails =
      ongoing
        ? `
          <h3>👶 Pregnancy Age</h3>

          <div class="grid">

            <div class="stat">
              <strong>${result.weeks}</strong>
              <span>Weeks</span>
            </div>

            <div class="stat">
              <strong>${result.days}</strong>
              <span>Days</span>
            </div>

            <div class="stat">
              <strong>${result.pregnancyDays}</strong>
              <span>Total Days</span>
            </div>

          </div>

          <h3>🌸 Current Trimester</h3>

          <div class="trimester box">
            <strong>${result.trimester.name}</strong>
            <span>${result.trimester.description}</span>
          </div>

          <h3>📊 Pregnancy Progress</h3>

          <div class="progress box">

            <div class="progress-top">
              <span>Progress</span>
              <strong>${result.progressPercent}%</strong>
            </div>

            <div class="track">
              <div
                class="fill"
                style="width:${result.progressPercent}%"
              ></div>
            </div>

          </div>

          ${remaining}
        `
        : `
          <div class="not-started box">
            <strong>🌼 Pregnancy Not Started</strong>
            <p>${result.message}</p>
          </div>
        `;

    return `
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<meta
  name="viewport"
  content="width=device-width, initial-scale=1.0"
>

<title>AgeVerse Pregnancy Result</title>

<style>

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 30px 16px;
  background: #f1f5f9;
  color: #334155;
  font-family:
    Arial,
    Helvetica,
    sans-serif;
}

.container {
  width: 100%;
  max-width: 760px;
  margin: auto;
  background: #ffffff;
  border: 1px solid #e2e8f0;
  border-radius: 22px;
  padding: 24px;
  box-shadow:
    0 16px 38px
    rgba(15, 23, 42, .08);
}

.header {
  display: flex;
  align-items: center;
  gap: 14px;
  padding-bottom: 18px;
  border-bottom: 1px solid #e5e7eb;
}

.icon {
  width: 52px;
  height: 52px;
  border-radius: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
  background:
    linear-gradient(
      135deg,
      #fce7f3,
      #f5f3ff
    );
  font-size: 28px;
}

h1 {
  margin: 0;
  color: #1e1b4b;
  font-size: 22px;
}

.subtitle {
  margin-top: 4px;
  color: #64748b;
  font-size: 12px;
}

.box {
  border-radius: 16px;
  padding: 15px;
  margin-top: 12px;
}

.date {
  text-align: center;
  background:
    linear-gradient(
      135deg,
      #fdf2f8,
      #f8fafc
    );
  border: 1px solid #fbcfe8;
}

.due {
  text-align: center;
  background:
    linear-gradient(
      135deg,
      #eef2ff,
      #f5f3ff
    );
  border: 1px solid #e0e7ff;
}

.label {
  font-size: 11px;
  font-weight: 800;
}

.date .label {
  color: #be185d;
}

.due .label {
  color: #6366f1;
}

.date .value,
.due .value {
  display: block;
  margin-top: 5px;
  font-size: 21px;
  font-weight: 850;
}

.date .value {
  color: #9d174d;
}

.due .value {
  color: #312e81;
}

.sub {
  margin-top: 5px;
  color: #64748b;
  font-size: 10px;
}

h3 {
  margin:
    18px 0 8px;
  color: #334155;
  font-size: 14px;
}

.grid {
  display: grid;
  grid-template-columns:
    repeat(3, 1fr);
  gap: 10px;
}

.stat {
  min-height: 88px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  border-radius: 16px;
  background:
    linear-gradient(
      145deg,
      #fdf2f8,
      #f5f3ff
    );
  border: 1px solid #f3d0e2;
}

.stat strong {
  color: #be185d;
  font-size: 28px;
}

.stat span {
  margin-top: 6px;
  color: #64748b;
  font-size: 10px;
  font-weight: 700;
  text-transform: uppercase;
}

.trimester {
  text-align: center;
  background:
    linear-gradient(
      135deg,
      #fdf2f8,
      #fff7fb
    );
  border: 1px solid #fbcfe8;
}

.trimester strong {
  display: block;
  color: #9d174d;
  font-size: 16px;
}

.trimester span {
  display: block;
  margin-top: 5px;
  color: #64748b;
  font-size: 10px;
}

.progress {
  background: #f8fafc;
  border: 1px solid #e5e7eb;
}

.progress-top {
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
  color: #64748b;
  font-size: 11px;
  font-weight: 700;
}

.progress-top strong {
  color: #be185d;
}

.track {
  width: 100%;
  height: 9px;
  overflow: hidden;
  border-radius: 999px;
  background: #e2e8f0;
}

.fill {
  height: 100%;
  border-radius: 999px;
  background:
    linear-gradient(
      90deg,
      #ec4899,
      #8b5cf6
    );
}

.remaining {
  text-align: center;
  background:
    linear-gradient(
      135deg,
      #eff6ff,
      #f8fafc
    );
  border: 1px solid #dbeafe;
}

.remaining .label {
  color: #1d4ed8;
}

.remaining .value {
  margin-top: 5px;
  color: #1e40af;
  font-size: 21px;
  font-weight: 850;
}

.not-started {
  text-align: center;
  background:
    linear-gradient(
      135deg,
      #fff7ed,
      #fffbeb
    );
  border: 1px solid #fed7aa;
}

.not-started strong {
  color: #9a3412;
}

.not-started p {
  color: #64748b;
  font-size: 11px;
  line-height: 1.5;
}

.disclaimer {
  margin-top: 18px;
  padding: 12px;
  border-radius: 13px;
  background: #f8fafc;
  border: 1px solid #e5e7eb;
}

.disclaimer strong {
  color: #475569;
  font-size: 10px;
}

.disclaimer p {
  margin: 5px 0 0;
  color: #64748b;
  font-size: 9px;
  line-height: 1.5;
}

.footer {
  margin-top: 18px;
  padding-top: 12px;
  border-top: 1px solid #e5e7eb;
  text-align: center;
  color: #94a3b8;
  font-size: 10px;
}

.footer strong {
  color: #6366f1;
}

@media (max-width: 600px) {

  body {
    padding: 12px 8px;
  }

  .container {
    padding: 17px;
    border-radius: 18px;
  }

  .grid {
    gap: 7px;
  }

  .stat {
    min-height: 75px;
  }

  .stat strong {
    font-size: 24px;
  }

}

@media print {

  body {
    padding: 0;
    background: #ffffff;
  }

  .container {
    max-width: none;
    box-shadow: none;
    border: none;
    border-radius: 0;
  }

}

</style>

</head>

<body>

<div class="container">

  <div class="header">

    <div class="icon">🤰</div>

    <div>
      <h1>Pregnancy Result</h1>
      <div class="subtitle">
        AgeVerse Pregnancy Calculator
      </div>
    </div>

  </div>

  <div class="box date">

    <div class="label">
      🩸 Last Menstrual Period
    </div>

    <span class="value">
      ${result.lmpDate}
    </span>

  </div>

  <div class="box due">

    <div class="label">
      📅 Estimated Due Date
    </div>

    <span class="value">
      ${result.dueDate}
    </span>

    <div class="sub">
      📌 ${result.dueDateWithDay}
    </div>

  </div>

  ${pregnancyDetails}

  <div class="disclaimer">

    <strong>ℹ️ Important</strong>

    <p>
      This calculator provides an estimated pregnancy
      timeline based on the date entered. It is intended
      for general informational purposes only and should
      not be used as a substitute for medical diagnosis,
      treatment, or advice from a qualified healthcare
      professional. Pregnancy dates can vary, and your
      healthcare provider should be consulted for accurate
      assessment and clinical decisions.
    </p>

  </div>

  <div class="footer">
    Generated by
    <strong>AgeVerse.Global</strong>
  </div>

</div>

</body>

</html>
`;
  }


  /* =========================================================
     PRINT
  ========================================================= */

  function handlePrint() {

    if (!result) return;

    setActionMessage(
      "Opening print preview..."
    );

    setTimeout(() => {

      window.print();

    }, 100);
  }


  /* =========================================================
     RESULT
  ========================================================= */

  function renderResult() {

    if (!result) {

      return (

        <div className="pregnancy-empty-result">

          <div className="pregnancy-empty-icon">
            🤰
          </div>

          <h2>
            {t("pregnancy.empty_title")}
          </h2>

          <p>
            {t("pregnancy.empty_text")}
          </p>

          <div className="pregnancy-empty-hint">
            {t("pregnancy.empty_hint")}
          </div>

        </div>

      );
    }


    return (

      <div className="pregnancy-result-card">

        <div className="pregnancy-result-header">

          <div className="pregnancy-result-icon">
            🤰
          </div>

          <div>

            <h2>
              Pregnancy Result
            </h2>

            <p>
              Your pregnancy timeline summary
            </p>

          </div>

        </div>


        <div className="pregnancy-date-panel">

          <span>
            🩸 Last Menstrual Period
          </span>

          <strong>
            {result.lmpDate}
          </strong>

        </div>


        <div className="pregnancy-due-date-panel">

          <span>
            📅 Estimated Due Date
          </span>

          <strong>
            {result.dueDate}
          </strong>

          <small>
            📌 {result.dueDateWithDay}
          </small>

        </div>


        {result.status === "not-started" && (

          <div className="pregnancy-status-box">

            <strong>
              🌼 Pregnancy Not Started
            </strong>

            <p>
              {result.message}
            </p>

          </div>

        )}


        {result.status !== "not-started" && (

          <>

            <div className="pregnancy-section-title">
              👶 Pregnancy Age
            </div>

            <div className="pregnancy-age-grid">

              <div className="pregnancy-age-box">
                <strong>
                  {result.weeks}
                </strong>
                <span>Weeks</span>
              </div>

              <div className="pregnancy-age-box">
                <strong>
                  {result.days}
                </strong>
                <span>Days</span>
              </div>

              <div className="pregnancy-age-box">
                <strong>
                  {result.pregnancyDays}
                </strong>
                <span>Total Days</span>
              </div>

            </div>


            <div className="pregnancy-section-title">
              🌸 Current Trimester
            </div>

            <div className="pregnancy-trimester-box">

              <strong>
                {result.trimester.name}
              </strong>

              <span>
                {result.trimester.description}
              </span>

            </div>


            <div className="pregnancy-section-title">
              📊 Pregnancy Progress
            </div>

            <div className="pregnancy-progress-box">

              <div className="pregnancy-progress-top">

                <span>
                  Progress
                </span>

                <strong>
                  {result.progressPercent}%
                </strong>

              </div>

              <div className="pregnancy-progress-track">

                <div
                  className="pregnancy-progress-fill"
                  style={{
                    width:
                      `${result.progressPercent}%`,
                  }}
                />

              </div>

            </div>


            {result.status === "ongoing" && (

              <div className="pregnancy-remaining-box">

                <span>
                  ⏳ Estimated time remaining
                </span>

                <strong>
                  {result.remainingDays} Days
                </strong>

                <small>
                  Until estimated due date
                </small>

              </div>

            )}


            {result.status === "due-or-past" && (

              <div className="pregnancy-due-status">

                <strong>
                  🎉 Estimated Due Date Reached
                </strong>

                <p>
                  {result.message}
                </p>

              </div>

            )}

          </>

        )}


        <div className="pregnancy-disclaimer">

          <strong>
            ℹ️ Important
          </strong>

          <p>
            This calculator provides an estimated
            pregnancy timeline based on the date entered.
            It is intended for general informational
            purposes only and should not be used as a
            substitute for medical diagnosis, treatment,
            or advice from a qualified healthcare
            professional. Pregnancy dates can vary, and
            your healthcare provider should be consulted
            for accurate assessment and clinical decisions.
          </p>

        </div>


        <div className="pregnancy-result-actions">

          <button
            type="button"
            className="pregnancy-action-button pregnancy-copy-button"
            onClick={handleCopy}
          >
            📋 Copy Result
          </button>

          <button
            type="button"
            className="pregnancy-action-button pregnancy-share-button"
            onClick={handleShare}
          >
            📤 Share Result
          </button>

          <button
            type="button"
            className="pregnancy-action-button pregnancy-download-button"
            onClick={handleDownload}
          >
            📥 Download
          </button>

          <button
            type="button"
            className="pregnancy-action-button pregnancy-print-button"
            onClick={handlePrint}
          >
            🖨️ Print
          </button>

        </div>


        {actionMessage && (

          <div className="pregnancy-action-message">
            {actionMessage}
          </div>

        )}


        <div className="pregnancy-result-footer">
        <ResultAttribution type="generated" />
      </div>

      </div>

    );
  }


  /* =========================================================
     PAGE
  ========================================================= */

  return (

    <CalculatorLayout
      title="🤰 Pregnancy Calculator"
      subtitle={t("pregnancy.timeline_subtitle")}
      result={renderResult()}
    >

      <form
        className="pregnancy-card"
        onSubmit={handleCalculate}
      >

        <div className="pregnancy-field">

          <label>
            🩸 First Day of Last Menstrual Period
          </label>

          <DateInput
            value={lmpDate}
            onChange={(value) => {

              setLmpDate(value);
              setError("");
              setResult(null);
              setActionMessage("");

            }}
            resetKey={lmpResetKey}
          />

          <small>
            {t("pregnancy.lmp_help")}
          </small>

        </div>


        <div className="pregnancy-field">

          <label>
            📅 Calculate Pregnancy On
          </label>

          <DateInput
            value={calculationDate}
            onChange={(value) => {

              setCalculationDate(value);
              setError("");
              setResult(null);
              setActionMessage("");

            }}
            resetKey={calculationResetKey}
          />

          <small>
            Leave blank to calculate using today's date.
          </small>

        </div>


        {error && (

          <div
            className="pregnancy-error"
            role="alert"
          >
            ⚠️ {error}
          </div>

        )}


        <div className="pregnancy-buttons">

          <button
            type="submit"
            className="pregnancy-calculate-button"
          >
            🤰 Calculate Pregnancy
          </button>

          <button
            type="button"
            className="pregnancy-reset-button"
            onClick={handleReset}
          >
            ↻ Reset
          </button>

        </div>


        <div className="pregnancy-info">

          <strong>
            💡 How it works
          </strong>

          <p>
            {t("pregnancy.calculation_note_full")}
          </p>

        </div>

      </form>

    </CalculatorLayout>

  );
}


export default PregnancyCalculator;