import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import BmiGauge from "./BmiGauge";

function HealthProfileResultCard({ result }) {
  const { t, i18n } = useTranslation();
  const [animatedScore, setAnimatedScore] = useState(0);

  /*
   * =========================================================
   * LANGUAGE
   * =========================================================
   *
   * Language-sensitive units are resolved through i18n first.
   * This keeps the component ready for additional languages:
   * add the same unit keys to the new locale without changing
   * this component.
   */
  const language =
    (i18n.language || i18n.resolvedLanguage || "en").split("-")[0];

  const isHindi =
    language === "hi" ||
    language.startsWith("hi-");

  /*
   * =========================================================
   * LOCALIZED UNITS
   * =========================================================
   *
   * Existing translation keys:
   *   g -> English: g / Hindi: ग्राम
   *   L -> English: L / Hindi: लीटर
   *
   * kg is kept with a safe Hindi fallback because the current
   * Hindi source does not require a separate "kg" key yet.
   * Future languages can simply add "kg" to their locale.
   */
  const getUnit = (key, fallback) => {
    const value = i18n.getResource(
      language,
      "translation",
      key
    );

    return typeof value === "string" && value.trim()
      ? value
      : fallback;
  };

  const unitGram = getUnit("g", "g");
  const unitLiter = getUnit("L", "L");
  const unitKg = getUnit("kg", isHindi ? "किग्रा" : "kg");
  const unitDay = getUnit("day", isHindi ? "दिन" : "day");

  /*
   * =========================================================
   * IDEAL WEIGHT FORMAT
   * =========================================================
   */
  function formatIdealWeight(value) {
    if (value === null || value === undefined) {
      return "";
    }

    const text = String(value).trim();

    if (!text) {
      return "";
    }

    return text.replace(
      /\s*kg\b/gi,
      ` ${unitKg}`
    );
  }

  /*
   * =========================================================
   * GENERATED BY
   * =========================================================
   *
   * Uses the translation key so newly added languages can
   * provide their own wording without changing this file.
   */
  const generatedBy = t("✨ Generated by", {
    defaultValue: isHindi
      ? "✨ AgeVerse.Global द्वारा जनरेट किया गया"
      : "✨ Generated by AgeVerse.Global",
  });

  /*
   * =========================================================
   * WELLNESS SCORE ANIMATION
   * =========================================================
   */
  useEffect(() => {
    if (!result) {
      return;
    }

    const rawScore = Number(result.healthScore);

    const endScore = Number.isFinite(rawScore)
      ? Math.min(
          100,
          Math.max(
            0,
            Math.round(rawScore)
          )
        )
      : 0;

    const delay = 300;
    const duration = 1800;

    const startedAt =
      performance.now() + delay;

    let timerId = null;

    const resetTimerId =
      window.setTimeout(() => {
        setAnimatedScore(0);
      }, 0);

    const updateScore = () => {
      const now = performance.now();

      if (now < startedAt) {
        setAnimatedScore(0);

        timerId =
          window.setTimeout(
            updateScore,
            16
          );

        return;
      }

      const progress =
        Math.min(
          (now - startedAt) /
            duration,
          1
        );

      const easedProgress =
        1 -
        Math.pow(
          1 - progress,
          3
        );

      const currentScore =
        Math.min(
          endScore,
          Math.round(
            endScore *
              easedProgress
          )
        );

      setAnimatedScore(
        currentScore
      );

      if (progress < 1) {
        timerId =
          window.setTimeout(
            updateScore,
            16
          );
      } else {
        setAnimatedScore(
          endScore
        );
      }
    };

    timerId =
      window.setTimeout(
        updateScore,
        16
      );

    return () => {
      window.clearTimeout(
        resetTimerId
      );

      if (timerId !== null) {
        window.clearTimeout(
          timerId
        );
      }
    };
  }, [result]);

  if (!result) {
    return null;
  }

  /*
   * =========================================================
   * HEALTH SCORE
   * =========================================================
   */
  const rawHealthScore =
    Number(result.healthScore);

  const wellnessScore =
    Number.isFinite(
      rawHealthScore
    )
      ? Math.min(
          100,
          Math.max(
            0,
            Math.round(
              rawHealthScore
            )
          )
        )
      : 0;

  /*
   * =========================================================
   * SCORE COLOR
   * =========================================================
   */
  const scoreClass =
    wellnessScore >= 75
      ? "wellness-progress-good"
      : wellnessScore >= 60
        ? "wellness-progress-warning"
        : "wellness-progress-danger";

  /*
   * =========================================================
   * DISPLAY NAME
   * =========================================================
   */
  const displayName =
    result.name &&
    result.name.trim() !== ""
      ? result.name
      : "";

  return (
    <div className="health-result-card">

      {/* ============================================
          WELLNESS HEADER
      ============================================ */}

      <div className="wellness-summary">

        <div className="wellness-intro">

          <div className="wellness-greeting">
            👋 {t("Hello")}
            {displayName
              ? ` ${displayName}`
              : ""}
            !
          </div>

          <div className="wellness-subtitle">
            {t("Your Overall Wellness")}
          </div>

          <div className="wellness-status">

            <span className="wellness-icon">
              {result.wellnessIcon}
            </span>

            <span>
              {result.wellnessStatus}
            </span>

          </div>

        </div>


        {/* CENTER — WELLNESS SCORE */}

        <div className="wellness-score-area">

          <div className="wellness-score-number">
            {animatedScore}/100
          </div>

          <div className="wellness-score-label">
            {t("Wellness Score")}
          </div>

          <div className="wellness-bar">

            <div
              className={`wellness-progress ${scoreClass}`}
              style={{
                width: `${animatedScore}%`,
              }}
            />

          </div>

          <div className="score-text">
            ✨ {result.wellnessMessage}
          </div>

        </div>


        {/* RIGHT — WELLNESS LOGO */}

        <div className="wellness-logo">

          <img
            src={`${import.meta.env.BASE_URL}images/wellness-shield.jpg`}
            alt={t("Wellness Shield")}
          />

        </div>

      </div>


      {/* ============================================
          HEALTH SUMMARY
      ============================================ */}

      <div className="health-header">

        <h2>
          {t("📊 Health Summary")}
        </h2>

        <p>
          {t(
            "Your personalized wellness report"
          )}
        </p>

      </div>


      <div className="health-grid-result">

        <div className="health-box">

          <span>
            {t("⚖️ BMI")}
          </span>

          <strong>
            {result.bmi}
          </strong>

          <small>
            {result.bmiStatus}
          </small>

        </div>


        <div className="health-box">

          <span>
            {t("🔥 BMR")}
          </span>

          <strong>
            {result.bmr}
          </strong>

          <small>
            kcal/day
          </small>

        </div>


        <div className="health-box">

          <span>
            {t("♡ Calories")}
          </span>

          <strong>
            {result.calories}
          </strong>

          <small>
            kcal/day
          </small>

        </div>


        {/* WATER */}

        <div className="health-box">

          <span>
            {t("💧 Water")}
          </span>

          <strong>
            {result.water}
          </strong>

          <small>
            {unitLiter}/{unitDay}
          </small>

        </div>


        {/* IDEAL WEIGHT */}

        <div className="health-box">

          <span>
            {t("🎯 Ideal Weight")}
          </span>

          <strong>
            {formatIdealWeight(
              result.idealWeight
            )}
          </strong>

          <small>
            {t("Healthy Range")}
          </small>

        </div>


        <div className="health-box">

          <span>
            {t("🏃 Body Age")}
          </span>

          <strong>
            {result.bodyAge}
          </strong>

          <small>
            {t("Matches real age")}
          </small>

        </div>


        {/* PROTEIN */}

        <div className="health-box">

          <span>
            {t("🥩 Protein")}
          </span>

          <strong>
            {result.protein} {unitGram}
          </strong>

          <small>
            {t("daily")}
          </small>

        </div>


        {/* CARBS */}

        <div className="health-box">

          <span>
            {t("🍲 Carbs")}
          </span>

          <strong>
            {result.carbs} {unitGram}
          </strong>

          <small>
            {t("daily")}
          </small>

        </div>


        {/* FAT */}

        <div className="health-box">

          <span>
            {t("🥑 Fat")}
          </span>

          <strong>
            {result.fat} {unitGram}
          </strong>

          <small>
            {t("daily")}
          </small>

        </div>


        {/* HEALTH SCORE */}

        <div className="health-box">

          <span>
            {t("⭐ Health Score")}
          </span>

          <strong>
            {wellnessScore}/100
          </strong>

          <small>
            {result.wellnessStatus}
          </small>

        </div>

      </div>


      {/* ============================================
          BMI GAUGE
      ============================================ */}

      <BmiGauge
        bmi={result.bmi}
      />


      {/* ============================================
          NUTRITION / CHALLENGE / TIPS
      ============================================ */}

      <div className="health-three-column">

        {/* NUTRITION */}

        <div className="dashboard-card nutrition-dashboard">

          <h3>
            {t("🥗 Nutrition Balance")}
          </h3>

          <p className="dashboard-subtitle">
            {t(
              "Recommended daily nutrition"
            )}
          </p>

          <div className="nutrition-mini-grid">

            <div>

              <span>
                {t("🥩 Protein")}
              </span>

              <strong>
                {result.protein} {unitGram}
              </strong>

            </div>


            <div>

              <span>
                {t("🍲 Carbs")}
              </span>

              <strong>
                {result.carbs} {unitGram}
              </strong>

            </div>


            <div>

              <span>
                {t("🥑 Fat")}
              </span>

              <strong>
                {result.fat} {unitGram}
              </strong>

            </div>

          </div>

        </div>


        {/* CHALLENGE */}

        <div className="dashboard-card challenge-card">

          <h3>
            {t("🏆 Today's Challenge")}
          </h3>

          <ul>

            {result.challenge?.map(
              (item, index) => (
                <li key={index}>
                  {item}
                </li>
              )
            )}

          </ul>

        </div>


        {/* HEALTH TIPS */}

        <div className="dashboard-card health-tips">

          <h3>
            {t("💡 Smart Health Tips")}
          </h3>

          <ul>

            {result.tips?.map(
              (tip, index) => (
                <li key={index}>
                  {tip}
                </li>
              )
            )}

          </ul>

        </div>

      </div>


      {/* ============================================
          PERSONALIZED DIET PLAN
      ============================================ */}

      <div className="personalized-plan">

        <h3>
          {t("🍽️ Personalized Diet Plan")}
        </h3>

        <p className="dashboard-subtitle">
          {t(
            "Food suggestions based on your selected diet"
          )}
        </p>

        <div className="food-list">

          {result.foods?.map(
            (food, index) => (
              <span
                className="food-item"
                key={index}
              >
                {food}
              </span>
            )
          )}

        </div>


        {/* LIFESTYLE */}

        <h3 className="lifestyle-title">
          {t("🌿 Daily Lifestyle Goals")}
        </h3>

        <div className="lifestyle-grid">

          <div>

            <span className="lifestyle-icon">
              😴
            </span>

            <strong>
              {t("Sleep:")}
            </strong>

            <span>
              7–8 {t("Hours")}
            </span>

          </div>


          <div>

            <span className="lifestyle-icon">
              🚶
            </span>

            <strong>
              {t("Steps:")}
            </strong>

            <span>
              8000 {t("Steps")}
            </span>

          </div>


          {/* WATER — SINGLE UNIT */}

          <div>

            <span className="lifestyle-icon">
              💧
            </span>

            <span>
              {result.water} {unitLiter}
            </span>

          </div>


          <div>

            <span className="lifestyle-icon">
              🥗
            </span>

            <strong>
              {t("Nutrition:")}
            </strong>

            <span>
              {t("Balanced Diet")}
            </span>

          </div>

        </div>

      </div>


      {/* ============================================
          DISCLAIMER
      ============================================ */}

      <div className="health-disclaimer">

        <span className="disclaimer-icon">
          ⓘ
        </span>

        <div>

          <strong>
            {t("Disclaimer:")}
          </strong>{" "}

          {t(
            "This wellness report is generated based on the information provided by the user and is intended for educational and general wellness purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment."
          )}

        </div>

      </div>


      {/* ============================================
          GENERATED BY
      ============================================ */}

      <div className="generated-by">

        <strong>
          {generatedBy}
        </strong>

      </div>

    </div>
  );
}

export default HealthProfileResultCard;
